[package]
name = "awse"
version = "0.1.0"
authors = ["bsoptei <bsoptei@gmail.com>"]
edition = "2018"

[dependencies]
actix-rt = "1.0.0"
actix-web = "3"
async-trait = "0.1.24"
futures = "0.3.13"
rand = "0.7.3"
serde = "1.0.104"
serde_json = "1.0.44"
